services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
#    volumes:
#      - ./backend/finance_vault.db:/finance_vault.db
#    volumes:
#      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
#    environment:
#      MB_DB_TYPE: postgres
#      MB_DB_DBNAME: metabaseappdb
#      MB_DB_PORT: 5432
#      MB_DB_USER: metabase
#      MB_DB_PASS: mysecretpassword
#      MB_DB_HOST: postgres
#    networks:
#      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
#  postgres:
#    image: postgres:16
#    container_name: postgres
#    hostname: postgres
#    environment:
#      POSTGRES_USER: metabase
#      POSTGRES_DB: metabaseappdb
#      POSTGRES_PASSWORD: mysecretpassword
#    volumes:
#      - ./pg_data:/var/lib/postgresql/data
#    networks:
#      - metanet1
#networks:
#  metanet1:
#    driver: bridge
